### ISSUE TITLE
ts-gyb@0.4.1 cannot be installed though the latest version is 0.4.1 on npm

### ISSUE THREAD

**Issue by imWildCat** [microsoft/ts-gyb#61]
According to <https://www.npmjs.com/package/ts-gyb>, the latest version should be `0.4.1`.

However,

```shell
$ yarn add -D ts-gyb@0.4.1
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "ts-gyb" that matches "0.4.1"
```

**Comment by imWildCat** [comment]
I found a similar ticket (mentioned above) and filed a support ticket to npm.

**Comment by imWildCat** [comment]
Got a reply. I tried `npm install ts-gyb@0.4.1` according to their suggestion and it works.

Replied to ask the reason.

**Comment by zhuorantan** [comment]
I also encountered this. I thought it was a cache issue because I was trying minutes after I published. Specifying the version worked.

**Comment by imWildCat** [comment]
According to the linked issue mentioned above, it should be related to cache.

Let's move forward with #62 and then publish a new version.

**Comment by zhuorantan** [comment]
Does the version `v0.4.2-rc1` still have this issue?

**Comment by imWildCat** [comment]
> Does the version `v0.4.2-rc1` still have this issue?

No. But I'd like to wait one more day for their reply.

**Comment by imWildCat** [comment]
The npm team helped us to refresh the cache and the issue should be resolved.
